name: Deploy API Bot to GitHub

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'  # Déclenchement uniquement lors des modifications dans le dossier api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './api/package.json'
      
      - name: Install dependencies
        run: |
          cd api
          npm install
      
      - name: Start API Service
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 3000
        run: |
          cd api
          npm start
        # Note: Pour un déploiement réel, vous auriez besoin d'une solution comme PM2 
        # ou d'un service de déploiement comme Render, Heroku, etc.