name: Deploy API to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'  # Déclencher uniquement lors des modifications dans le dossier api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}  # Vous devrez configurer cette valeur secrète
          api-key: ${{ secrets.RENDER_API_KEY }}  # Vous devrez configurer cette valeur secrète