name: Deploy API Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'  # Déclencher uniquement lors des modifications dans le dossier api

# Permissions explicites pour GitHub Packages
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Convert repository name to lowercase
        id: repo-name
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=${REPO}" >> $GITHUB_ENV
          
      - name: Check package access
        run: |
          echo "Checking package access permissions for ${{ github.actor }}"
          echo "Repository: ${{ env.REPO_LOWER }}"
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/api:latest
            ghcr.io/${{ env.REPO_LOWER }}/api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Options supplémentaires pour éviter les problèmes d'authentification
          provenance: false
          
      - name: Verify image creation
        run: |
          echo "Image Docker créée et poussée vers GitHub Container Registry"
          echo "Image: ghcr.io/${{ env.REPO_LOWER }}/api:latest"